package com.candlestickschart.pollfirst;

import androidx.room.ColumnInfo;
import androidx.room.Entity;
import androidx.room.Ignore;
import androidx.room.PrimaryKey;

@Entity(tableName = "pollfirst")
public class PollFirstData {
    @PrimaryKey(autoGenerate = true)
    public int ids;
    @ColumnInfo(name = "user_id")
    public String user_id;
    @ColumnInfo(name = "user_mobile_no")
    public String user_mobile_no;
    @ColumnInfo(name = "c_1")
    public String c_1;
    @ColumnInfo(name = "c_2")
    public String c_2;
    @ColumnInfo(name = "c_3")
    public String c_3;
    @ColumnInfo(name = "c_4")
    public String c_4;
    @ColumnInfo(name = "c_5")
    public String c_5;
    @ColumnInfo(name = "c_6")
    public String c_6;
    @ColumnInfo(name = "c_7")
    public String c_7;
    @ColumnInfo(name = "c_8")
    public String c_8;
    @ColumnInfo(name = "c_9")
    public String c_9;
    @ColumnInfo(name = "c_10")
    public String c_10;
    @ColumnInfo(name = "c_11")
    public String c_11;
    @ColumnInfo(name = "c_12")
    public String c_12;
    @ColumnInfo(name = "category")
    public String category;
    @ColumnInfo(name = "q_1")
    public String q_1;
    @ColumnInfo(name = "q_2_1")
    public String q_2_1;
    @ColumnInfo(name = "q_2_2")
    public String q_2_2;
    @ColumnInfo(name = "q_2_3")
    public String q_2_3;
    @ColumnInfo(name = "q_2_4")
    public String q_2_4;
    @ColumnInfo(name = "q_2_5")
    public String q_2_5;
    @ColumnInfo(name = "q_2_6")
    public String q_2_6;
    @ColumnInfo(name = "q_2_7")
    public String q_2_7;
    @ColumnInfo(name = "q_2_8")
    public String q_2_8;
    @ColumnInfo(name = "q_2_9")
    public String q_2_9;
    @ColumnInfo(name = "q_2_10")
    public String q_2_10;
    @ColumnInfo(name = "q_2_11")
    public String q_2_11;
    @ColumnInfo(name = "q_2_12")
    public String q_2_12;
    @ColumnInfo(name = "q_3")
    public String q_3;
    @ColumnInfo(name = "q_4")
    public String q_4;
    @ColumnInfo(name = "q_5")
    public String q_5;
    @ColumnInfo(name = "q_6")
    public String q_6;
    @ColumnInfo(name = "q_7")
    public String q_7;
    @ColumnInfo(name = "q_8")
    public String q_8;
    @ColumnInfo(name = "q_9")
    public String q_9;
    @ColumnInfo(name = "q_10")
    public String q_10;
    @ColumnInfo(name = "q_11")
    public String q_11;
    @ColumnInfo(name = "q_12")
    public String q_12;
    @ColumnInfo(name = "q_13")
    public String q_13;
    @ColumnInfo(name = "q_14")
    public String q_14;
    @ColumnInfo(name = "q_15")
    public String q_15;
    @ColumnInfo(name = "q_16")
    public String q_16;
    @ColumnInfo(name = "q_17")
    public String q_17;
    @ColumnInfo(name = "q_18")
    public String q_18;
    @ColumnInfo(name = "q_19")
    public String q_19;
    @ColumnInfo(name = "q_20_1")
    public String q_20_1;
    @ColumnInfo(name = "q_20_2")
    public String q_20_2;
    @ColumnInfo(name = "q_20_3")
    public String q_20_3;
    @ColumnInfo(name = "q_20_4")
    public String q_20_4;
    @ColumnInfo(name = "q_20_5")
    public String q_20_5;
    @ColumnInfo(name = "q_20_6")
    public String q_20_6;
    @ColumnInfo(name = "q_20_7")
    public String q_20_7;
    @ColumnInfo(name = "q_20_8")
    public String q_20_8;
    @ColumnInfo(name = "name")
    public String name;
    @ColumnInfo(name = "mobile_no")
    public String mobile_no;
    @ColumnInfo(name = "location")
    public String location;
    @ColumnInfo(name = "home_photo")
    public String home_photo;

    public PollFirstData(int ids, String user_id,String user_mobile_no, String c_1,String c_2, String c_3, String c_4, String c_5, String c_6, String c_7, String c_8, String c_9, String c_10, String c_11, String c_12,String category, String q_1, String q_2_1, String q_2_2, String q_2_3, String q_2_4, String q_2_5, String q_2_6, String q_2_7, String q_2_8, String q_2_9, String q_2_10, String q_2_11,String q_2_12, String q_3, String q_4, String q_5, String q_6, String q_7, String q_8, String q_9, String q_10, String q_11, String q_12, String q_13, String q_14,String q_15,String q_16,String q_17,String q_18,String q_19,String q_20_1,String q_20_2,String q_20_3,String q_20_4,String q_20_5,String q_20_6,String q_20_7,String q_20_8, String name, String location, String mobile_no, String home_photo){
        this.ids = ids;
        this.user_id = user_id;
        this.user_mobile_no = user_mobile_no;
        this.c_1 = c_1;
        this.c_2 = c_2;
        this.c_3 = c_3;
        this.c_4 = c_4;
        this.c_5 = c_5;
        this.c_6 = c_6;
        this.c_7 = c_7;
        this.c_8 = c_8;
        this.c_9 = c_9;
        this.c_10 = c_10;
        this.c_11 = c_11;
        this.c_12 = c_12;
        this.category = category;
        this.q_1 = q_1;
        this.q_2_1 = q_2_1;
        this.q_2_2 = q_2_2;
        this.q_2_3 = q_2_3;
        this.q_2_4 = q_2_4;
        this.q_2_5 = q_2_5;
        this.q_2_6 = q_2_6;
        this.q_2_7 = q_2_7;
        this.q_2_8 = q_2_8;
        this.q_2_9 = q_2_9;
        this.q_2_10 = q_2_10;
        this.q_2_11 = q_2_11;
        this.q_2_12 = q_2_12;
        this.q_3 = q_3;
        this.q_4 = q_4;
        this.q_5 = q_5;
        this.q_6 = q_6;
        this.q_7 = q_7;
        this.q_8 = q_8;
        this.q_9 = q_9;
        this.q_10 = q_10;
        this.q_11 = q_11;
        this.q_12 = q_12;
        this.q_13 = q_13;
        this.q_14 = q_14;
        this.q_15 = q_15;
        this.q_16 = q_16;
        this.q_17 = q_17;
        this.q_18 = q_18;
        this.q_19 = q_19;
        this.q_20_1 = q_20_1;
        this.q_20_2 = q_20_2;
        this.q_20_3 = q_20_3;
        this.q_20_4 = q_20_4;
        this.q_20_5 = q_20_5;
        this.q_20_6 = q_20_6;
        this.q_20_7 = q_20_7;
        this.q_20_8 = q_20_8;

        this.name = name;
        this.mobile_no = mobile_no;
        this.location = location;
        this.home_photo = home_photo;
    }

    @Ignore
    public PollFirstData(String user_id,String user_mobile_no, String c_1,String c_2, String c_3, String c_4, String c_5, String c_6, String c_7, String c_8, String c_9, String c_10, String c_11, String c_12,String category, String q_1, String q_2_1, String q_2_2, String q_2_3, String q_2_4, String q_2_5, String q_2_6, String q_2_7, String q_2_8, String q_2_9, String q_2_10, String q_2_11,String q_2_12, String q_3, String q_4, String q_5, String q_6, String q_7, String q_8, String q_9, String q_10, String q_11, String q_12, String q_13, String q_14,String q_15,String q_16,String q_17,String q_18,String q_19,String q_20_1,String q_20_2,String q_20_3,String q_20_4,String q_20_5,String q_20_6,String q_20_7,String q_20_8, String name, String location, String mobile_no, String home_photo){
        this.user_id = user_id;
        this.user_mobile_no = user_mobile_no;
        this.c_1 = c_1;
        this.c_2 = c_2;
        this.c_3 = c_3;
        this.c_4 = c_4;
        this.c_5 = c_5;
        this.c_6 = c_6;
        this.c_7 = c_7;
        this.c_8 = c_8;
        this.c_9 = c_9;
        this.c_10 = c_10;
        this.c_11 = c_11;
        this.c_12 = c_12;
        this.category = category;
        this.q_1 = q_1;
        this.q_2_1 = q_2_1;
        this.q_2_2 = q_2_2;
        this.q_2_3 = q_2_3;
        this.q_2_4 = q_2_4;
        this.q_2_5 = q_2_5;
        this.q_2_6 = q_2_6;
        this.q_2_7 = q_2_7;
        this.q_2_8 = q_2_8;
        this.q_2_9 = q_2_9;
        this.q_2_10 = q_2_10;
        this.q_2_11 = q_2_11;
        this.q_2_12 = q_2_12;
        this.q_3 = q_3;
        this.q_4 = q_4;
        this.q_5 = q_5;
        this.q_6 = q_6;
        this.q_7 = q_7;
        this.q_8 = q_8;
        this.q_9 = q_9;
        this.q_10 = q_10;
        this.q_11 = q_11;
        this.q_12 = q_12;
        this.q_13 = q_13;
        this.q_14 = q_14;
        this.q_15 = q_15;
        this.q_16 = q_16;
        this.q_17 = q_17;
        this.q_18 = q_18;
        this.q_19 = q_19;
        this.q_20_1 = q_20_1;
        this.q_20_2 = q_20_2;
        this.q_20_3 = q_20_3;
        this.q_20_4 = q_20_4;
        this.q_20_5 = q_20_5;
        this.q_20_6 = q_20_6;
        this.q_20_7 = q_20_7;
        this.q_20_8 = q_20_8;
        this.name = name;
        this.mobile_no = mobile_no;
        this.location = location;
        this.home_photo = home_photo;
    }
}
